// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ExtendedIsolationForest
NumericVector ExtendedIsolationForest(NumericMatrix M, int K, int N, double limit, int extensionLevel);
RcppExport SEXP _iforests_ExtendedIsolationForest(SEXP MSEXP, SEXP KSEXP, SEXP NSEXP, SEXP limitSEXP, SEXP extensionLevelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type limit(limitSEXP);
    Rcpp::traits::input_parameter< int >::type extensionLevel(extensionLevelSEXP);
    rcpp_result_gen = Rcpp::wrap(ExtendedIsolationForest(M, K, N, limit, extensionLevel));
    return rcpp_result_gen;
END_RCPP
}
// IsolationForest
NumericVector IsolationForest(NumericMatrix M, int K, int N, double limit);
RcppExport SEXP _iforests_IsolationForest(SEXP MSEXP, SEXP KSEXP, SEXP NSEXP, SEXP limitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type limit(limitSEXP);
    rcpp_result_gen = Rcpp::wrap(IsolationForest(M, K, N, limit));
    return rcpp_result_gen;
END_RCPP
}
// XIsolationForest
NumericVector XIsolationForest(NumericMatrix M, int K, int N, double limit);
RcppExport SEXP _iforests_XIsolationForest(SEXP MSEXP, SEXP KSEXP, SEXP NSEXP, SEXP limitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type limit(limitSEXP);
    rcpp_result_gen = Rcpp::wrap(XIsolationForest(M, K, N, limit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_iforests_ExtendedIsolationForest", (DL_FUNC) &_iforests_ExtendedIsolationForest, 5},
    {"_iforests_IsolationForest", (DL_FUNC) &_iforests_IsolationForest, 4},
    {"_iforests_XIsolationForest", (DL_FUNC) &_iforests_XIsolationForest, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_iforests(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
