# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ExtendedIsolationForest <- function(M, K = 200L, N = 512L, limit = 0, extensionLevel = 0L) {
    .Call(`_iforests_ExtendedIsolationForest`, M, K, N, limit, extensionLevel)
}

IsolationForest <- function(M, K = 200L, N = 512L, limit = 0) {
    .Call(`_iforests_IsolationForest`, M, K, N, limit)
}

XIsolationForest <- function(M, K = 200L, N = 512L, limit = 0) {
    .Call(`_iforests_XIsolationForest`, M, K, N, limit)
}

